export const rateCardsData = [
    {
        mode: 'mobile',
        bgColor: 'bg-orange',
        border: 'orange',
        headerText: 'Для небольшого исследования',
        iconType: 'lamp',
        iconPath: './lamp-icon.svg',
        current: '799 ₽',
        prev: '1200 ₽',
        creditConditions: 'или 150 ₽/мес. при рассрочке на 24 мес.',
        cardList: ['Безлимитная история запросов', 'Безопасная сделка', 'Поддержка 24/7'],
        currentRate: 'Beginner',
    },
    {
        mode: null,
        bgColor: 'bg-cyan',
        border: 'cyan',
        headerText: 'Для HR и фрилансеров',
        iconType: 'target',
        iconPath: './target-icon.svg',
        current: '1299 ₽',
        prev: '2600 ₽',
        creditConditions: 'или 279 ₽/мес. при рассрочке на 24 мес.',
        cardList: ['Все пункты тарифа Beginner', 'Экспорт истории', 'Рекомендации по приоритетам'],
        currentRate: 'Pro',
    },
    {
        mode: null,
        bgColor: 'bg-black',
        border: 'black',
        headerText: 'Для корпоративных клиентов',
        iconType: 'laptop',
        iconPath: './laptop-icon.svg',
        current: '2379 ₽',
        prev: '3700 ₽',
        creditConditions: null,
        cardList: ['Все пункты тарифа Pro', 'Безлимитное количество запросов', 'Приоритетная поддержка'],
        currentRate: 'Business',
    },
];
